### ISSUE TITLE
New release 0.9.4

### ISSUE THREAD

**Issue by bookingtechnology** [difi/asic#13]
Hi. 

Could you please make a new release with the changes since 0.9.3? 
The keyStoreType is a nice change :+1: 

Thanks

**Comment by steinarhenriksen** [comment]
Hi.

As you can tell this library hasn't been maintained for the past few years. I'm not sure why that's the case. We'll need to consider if and how we'll maintain the library going forward. We'll either maintain it properly or recommend an actively maintained alternative.

For now we'll update dependencies and provide a new version.
